version: "3.7"
services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_app
    environment:
      - POSTGRES_USER=${DB_USER} # Default superuser name in PostgreSQL. Change as needed.
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGUSER=${DB_USER} # The PostgreSQL username to be used by the application and healthcheck.
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ../weatherbuddy_pgdata:/var/lib/postgresql/data # Moved 'pgdata' dir outside the project to avoid unintended code monitoring, enhance security, ease backup & restore, isolate from code conflicts.

  redis:
    image: redis:7
    container_name: redis_app
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    env_file:
      - .env.prod
    container_name: fastapi_app
    command:
      - sh
      - -c
      - |
        alembic upgrade head
        uvicorn src.main:app --host 0.0.0.0 --port 1235
    ports:
      - 9999:1235
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1235"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:6.0.6
    container_name: mongo_app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-seed:
    build:
      context: ./mongo_seed
      args:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    container_name: mongo_seed
    depends_on:
      mongodb:
        condition: service_healthy

  celery:
    build: .
    env_file:
      - .env.prod
    container_name: celery_app
    command: celery -A src.celery_app:celery worker -l INFO
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "celery -A src.celery_app inspect ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  flower:
    build: .
    env_file:
      - .env.prod
    container_name: flower_app
    command: celery -A src.celery_app:celery flower
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_healthy
    ports:
      - 4444:5555
