"""added latitude and longitude columns into city table

Revision ID: 4130a96130a7
Revises: 800cc141a2cc
Create Date: 2023-05-24 11:14:31.277159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4130a96130a7'
down_revision = '800cc141a2cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('city', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'longitude')
    op.drop_column('city', 'latitude')
    # ### end Alembic commands ###
