"""created new table city

Revision ID: 800cc141a2cc
Revises: 1f30a498702c
Create Date: 2023-05-23 20:13:21.599073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800cc141a2cc'
down_revision = '1f30a498702c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    # ### end Alembic commands ###
