"""added city foreign key to user table

Revision ID: 92261d45cc34
Revises: 0cc507cfd19e
Create Date: 2023-05-26 21:35:45.173190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92261d45cc34'
down_revision = '0cc507cfd19e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'city', ['city_id'], ['id'])
    op.drop_column('user', 'city')
    op.drop_column('user', 'country')
    op.drop_column('user', 'longitude')
    op.drop_column('user', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'city_id')
    # ### end Alembic commands ###
