"""added disabled column in table user

Revision ID: 316710db929a
Revises: ba6924ec0a12
Create Date: 2023-03-21 12:48:47.500617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316710db929a'
down_revision = 'ba6924ec0a12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###
