"""added population, timezone and alternatenames columns into city table

Revision ID: 0cc507cfd19e
Revises: 4130a96130a7
Create Date: 2023-05-24 11:24:03.758977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc507cfd19e'
down_revision = '4130a96130a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('population', sa.Integer(), nullable=True))
    op.add_column('city', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('city', sa.Column('alternatenames', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'alternatenames')
    op.drop_column('city', 'timezone')
    op.drop_column('city', 'population')
    # ### end Alembic commands ###
